"""
Regional customer pool for the cold-chain operation of CD Itajaí (SC).

Every customer is a food retailer that receives refrigerated goods: supermarkets,
wholesalers, grocery stores, mini-markets, bakeries, butchers, fishmongers,
greengrocers and convenience stores across Itajaí, Balneário Camboriú, Camboriú,
Navegantes, Penha, Piçarras and Brusque.

Coordinates are approximate neighbourhood-level locations, adequate for routing demos.
Business names are illustrative.
"""

import hashlib
from typing import Any

# Customer segments (drive order size, time windows and dock behaviour)
SUPERMERCADO = "SUPERMERCADO"
ATACADO = "ATACADO"
MERCEARIA = "MERCEARIA"
MINIMERCADO = "MINIMERCADO"
PADARIA = "PADARIA"
ACOUGUE = "ACOUGUE"
PEIXARIA = "PEIXARIA"
HORTIFRUTI = "HORTIFRUTI"
CONVENIENCIA = "CONVENIENCIA"
SORVETERIA = "SORVETERIA"

SEGMENTS = (
    SUPERMERCADO,
    ATACADO,
    MERCEARIA,
    MINIMERCADO,
    PADARIA,
    ACOUGUE,
    PEIXARIA,
    HORTIFRUTI,
    CONVENIENCIA,
    SORVETERIA,
)

_VUC_ONLY_RULE = {
    "category": "ACCESS_RESTRICTION",
    "content": "Rua estreita e sem doca. Apenas veículos VUC autorizados; proibido Toco e Truck.",
    "priority": "CRITICAL",
}
_EARLY_DOCK_RULE = {
    "category": "DOCK_WINDOW",
    "content": "Recebimento de perecíveis somente antes da abertura da loja (até 09:00).",
    "priority": "HIGH",
}
_MORNING_DOCK_RULE = {
    "category": "DOCK_WINDOW",
    "content": "Doca de refrigerados opera apenas no período da manhã (até 12:00).",
    "priority": "HIGH",
}
_COLD_CHAIN_RULE = {
    "category": "COLD_CHAIN",
    "content": "Conferência de temperatura obrigatória na doca (resfriados 0-4 °C, congelados -18 °C). Registro no canhoto.",
    "priority": "HIGH",
}
_QUICK_UNLOAD_RULE = {
    "category": "ACCESS_RESTRICTION",
    "content": "Sem doca: descarga rápida na calçada, máximo 15 minutos de parada.",
    "priority": "HIGH",
}

# (code, name, segment, street, neighbourhood, city, zip, lat, lng, phone, dock_type, max_vehicle, rules)
_RAW: list[tuple[str, str, str, str, str, str, str, float, float, str, str, str, list[dict[str, str]]]] = [
    # ---------------------------------------------------------------- Itajaí
    (
        "CUST-ITJ-001",
        "Supermercado Bistek - Fazenda",
        SUPERMERCADO,
        "Rua Sete de Setembro, 1200",
        "Fazenda",
        "Itajaí",
        "88301-202",
        -26.9185,
        -48.6492,
        "(47) 3348-1000",
        "RAMPA_ESTREITA",
        "VUC",
        [_VUC_ONLY_RULE, _COLD_CHAIN_RULE],
    ),
    (
        "CUST-ITJ-002",
        "Komprão Koch Atacadista - Cordeiros",
        ATACADO,
        "Av. Reinaldo Schmithausen, 1850",
        "Cordeiros",
        "Itajaí",
        "88310-001",
        -26.8820,
        -48.6810,
        "(47) 3349-2200",
        "DOCA_ELEVADA",
        "TRUCK",
        [_MORNING_DOCK_RULE, _COLD_CHAIN_RULE],
    ),
    (
        "CUST-ITJ-003",
        "Angeloni Supermercados - Centro",
        SUPERMERCADO,
        "Av. Marcos Konder, 700",
        "Centro",
        "Itajaí",
        "88301-302",
        -26.9060,
        -48.6650,
        "(47) 3341-3300",
        "DOCA_ELEVADA",
        "TRUCK",
        [_COLD_CHAIN_RULE],
    ),
    (
        "CUST-ITJ-004",
        "Giassi Supermercados - Dom Bosco",
        SUPERMERCADO,
        "Rua Alberto Werner, 2000",
        "Dom Bosco",
        "Itajaí",
        "88307-000",
        -26.9235,
        -48.6700,
        "(47) 3346-4400",
        "DOCA_ELEVADA",
        "TRUCK",
        [],
    ),
    (
        "CUST-ITJ-005",
        "Mercearia São Vicente",
        MERCEARIA,
        "Rua Estefano José Vanolli, 920",
        "São Vicente",
        "Itajaí",
        "88309-500",
        -26.9045,
        -48.6935,
        "(47) 3247-5500",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    (
        "CUST-ITJ-006",
        "Minimercado Cidade Nova",
        MINIMERCADO,
        "Rua Alfredo Kroeger, 310",
        "Cidade Nova",
        "Itajaí",
        "88308-300",
        -26.9020,
        -48.7030,
        "(47) 3248-6600",
        "NIVEL_SOLO",
        "TOCO",
        [],
    ),
    (
        "CUST-ITJ-007",
        "Padaria & Confeitaria Praia Brava",
        PADARIA,
        "Av. José Medeiros Vieira, 500",
        "Praia Brava",
        "Itajaí",
        "88306-880",
        -26.9520,
        -48.6320,
        "(47) 3249-7700",
        "NIVEL_SOLO",
        "VUC",
        [_EARLY_DOCK_RULE, _VUC_ONLY_RULE],
    ),
    (
        "CUST-ITJ-008",
        "Açougue & Frios Vila Operária",
        ACOUGUE,
        "Rua Lauro Müller, 350",
        "Vila Operária",
        "Itajaí",
        "88303-100",
        -26.8960,
        -48.6740,
        "(47) 3344-8800",
        "NIVEL_SOLO",
        "TOCO",
        [_COLD_CHAIN_RULE],
    ),
    (
        "CUST-ITJ-009",
        "Hortifruti Vale - Espinheiros",
        HORTIFRUTI,
        "Rua Blumenau, 2200",
        "Espinheiros",
        "Itajaí",
        "88311-700",
        -26.9000,
        -48.7180,
        "(47) 3241-9900",
        "NIVEL_SOLO",
        "TOCO",
        [],
    ),
    (
        "CUST-ITJ-010",
        "Supermercado Cooper - São João",
        SUPERMERCADO,
        "Rua Uruguai, 1000",
        "São João",
        "Itajaí",
        "88304-200",
        -26.9200,
        -48.6600,
        "(47) 3345-1100",
        "DOCA_ELEVADA",
        "TRUCK",
        [],
    ),
    (
        "CUST-ITJ-011",
        "Mercado Público de Itajaí - Boxes de Pescados",
        PEIXARIA,
        "Rua Lauro Müller, 1",
        "Centro",
        "Itajaí",
        "88301-400",
        -26.9058,
        -48.6580,
        "(47) 3348-1200",
        "SEM_DOCA",
        "VUC",
        [_VUC_ONLY_RULE, _COLD_CHAIN_RULE],
    ),
    (
        "CUST-ITJ-012",
        "Empório & Frios Itaipava",
        MERCEARIA,
        "Rod. Antônio Heil, km 3",
        "Itaipava",
        "Itajaí",
        "88316-000",
        -26.9380,
        -48.7150,
        "(47) 3242-1300",
        "NIVEL_SOLO",
        "TOCO",
        [],
    ),
    (
        "CUST-ITJ-013",
        "Supermercado Imperatriz - Cordeiros",
        SUPERMERCADO,
        "Av. Reinaldo Schmithausen, 1200",
        "Cordeiros",
        "Itajaí",
        "88310-001",
        -26.8870,
        -48.6760,
        "(47) 3349-1400",
        "DOCA_ELEVADA",
        "TRUCK",
        [_COLD_CHAIN_RULE],
    ),
    (
        "CUST-ITJ-014",
        "Minimercado Bom Preço - Barra do Rio",
        MINIMERCADO,
        "Rua Almirante Barroso, 180",
        "Barra do Rio",
        "Itajaí",
        "88305-100",
        -26.9180,
        -48.6800,
        "(47) 3346-1500",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    (
        "CUST-ITJ-015",
        "Conveniência Posto Marcos Konder",
        CONVENIENCIA,
        "Av. Marcos Konder, 1500",
        "Centro",
        "Itajaí",
        "88301-303",
        -26.9090,
        -48.6700,
        "(47) 3341-1600",
        "SEM_DOCA",
        "VUC",
        [_QUICK_UNLOAD_RULE],
    ),
    (
        "CUST-ITJ-016",
        "Casa de Carnes Cordeiros",
        ACOUGUE,
        "Rua Nilo Peçanha, 640",
        "Cordeiros",
        "Itajaí",
        "88310-100",
        -26.8790,
        -48.6900,
        "(47) 3349-1700",
        "NIVEL_SOLO",
        "TOCO",
        [_COLD_CHAIN_RULE],
    ),
    (
        "CUST-ITJ-017",
        "Supermercado Bistek - Cidade Nova",
        SUPERMERCADO,
        "Rua Silva, 2500",
        "Cidade Nova",
        "Itajaí",
        "88308-200",
        -26.8980,
        -48.7080,
        "(47) 3248-1800",
        "DOCA_ELEVADA",
        "TRUCK",
        [],
    ),
    (
        "CUST-ITJ-018",
        "Sorveteria & Gelados Cabeçudas",
        SORVETERIA,
        "Av. Cabeçudas, 100",
        "Cabeçudas",
        "Itajaí",
        "88306-100",
        -26.9260,
        -48.6370,
        "(47) 3348-1900",
        "SEM_DOCA",
        "VUC",
        [_VUC_ONLY_RULE, _COLD_CHAIN_RULE],
    ),
    (
        "CUST-ITJ-019",
        "Minimercado Murta",
        MINIMERCADO,
        "Rua Hercílio Luz, 1800",
        "Murta",
        "Itajaí",
        "88311-200",
        -26.8880,
        -48.6960,
        "(47) 3247-2000",
        "NIVEL_SOLO",
        "TOCO",
        [],
    ),
    (
        "CUST-ITJ-020",
        "Casa de Carnes & Frios Ressacada",
        ACOUGUE,
        "Rua Ressacada, 420",
        "Ressacada",
        "Itajaí",
        "88307-400",
        -26.9300,
        -48.6900,
        "(47) 3346-2100",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    (
        "CUST-ITJ-021",
        "Supermercado Imperatriz - São Vicente",
        SUPERMERCADO,
        "Rua Adolfo Konder, 900",
        "São Vicente",
        "Itajaí",
        "88309-000",
        -26.9010,
        -48.6870,
        "(47) 3247-2200",
        "DOCA_ELEVADA",
        "TOCO",
        [],
    ),
    # ---------------------------------------------------- Balneário Camboriú
    (
        "CUST-BC-001",
        "Angeloni Supermercados - Quarta Avenida",
        SUPERMERCADO,
        "Quarta Avenida, 1500",
        "Centro",
        "Balneário Camboriú",
        "88330-110",
        -26.9910,
        -48.6350,
        "(47) 3363-1000",
        "DOCA_ELEVADA",
        "TRUCK",
        [_MORNING_DOCK_RULE],
    ),
    (
        "CUST-BC-002",
        "Supermercado De Angelina - Barra Norte",
        SUPERMERCADO,
        "Av. Normando Tedesco, 2100",
        "Barra Norte",
        "Balneário Camboriú",
        "88330-600",
        -26.9750,
        -48.6300,
        "(47) 3367-1100",
        "DOCA_ELEVADA",
        "TOCO",
        [],
    ),
    (
        "CUST-BC-003",
        "Supermercado Koch - Nações",
        SUPERMERCADO,
        "Rua 2000, 480",
        "Nações",
        "Balneário Camboriú",
        "88338-100",
        -26.9830,
        -48.6470,
        "(47) 3363-1200",
        "DOCA_ELEVADA",
        "TRUCK",
        [],
    ),
    (
        "CUST-BC-004",
        "Mercearia Pioneiros",
        MERCEARIA,
        "Rua 3100, 220",
        "Pioneiros",
        "Balneário Camboriú",
        "88331-000",
        -26.9860,
        -48.6420,
        "(47) 3366-1300",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    (
        "CUST-BC-005",
        "Minimercado Barra Sul",
        MINIMERCADO,
        "Av. do Estado, 5000",
        "Barra Sul",
        "Balneário Camboriú",
        "88330-000",
        -27.0050,
        -48.6250,
        "(47) 3367-1400",
        "SEM_DOCA",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    (
        "CUST-BC-006",
        "Padaria & Lanches Avenida Brasil",
        PADARIA,
        "Av. Brasil, 2000",
        "Centro",
        "Balneário Camboriú",
        "88330-050",
        -26.9950,
        -48.6370,
        "(47) 3363-1500",
        "SEM_DOCA",
        "VUC",
        [_EARLY_DOCK_RULE, _VUC_ONLY_RULE],
    ),
    (
        "CUST-BC-007",
        "Açougue & Frios Municípios",
        ACOUGUE,
        "Rua Suíça, 300",
        "Municípios",
        "Balneário Camboriú",
        "88337-000",
        -26.9780,
        -48.6600,
        "(47) 3360-1600",
        "NIVEL_SOLO",
        "TOCO",
        [_COLD_CHAIN_RULE],
    ),
    (
        "CUST-BC-008",
        "Hortifruti dos Estados",
        HORTIFRUTI,
        "Av. do Estado, 1200",
        "Dos Estados",
        "Balneário Camboriú",
        "88339-000",
        -26.9850,
        -48.6520,
        "(47) 3360-1700",
        "NIVEL_SOLO",
        "TOCO",
        [],
    ),
    (
        "CUST-BC-009",
        "Conveniência Praia Central",
        CONVENIENCIA,
        "Av. Atlântica, 3500",
        "Centro",
        "Balneário Camboriú",
        "88330-010",
        -26.9980,
        -48.6300,
        "(47) 3367-1800",
        "SEM_DOCA",
        "VUC",
        [_QUICK_UNLOAD_RULE, _VUC_ONLY_RULE],
    ),
    (
        "CUST-BC-010",
        "Giassi Supermercados - Vila Real",
        SUPERMERCADO,
        "Av. Santa Catarina, 900",
        "Vila Real",
        "Balneário Camboriú",
        "88337-200",
        -26.9880,
        -48.6560,
        "(47) 3360-1900",
        "DOCA_ELEVADA",
        "TRUCK",
        [],
    ),
    (
        "CUST-BC-011",
        "Supermercado Bistek - Barra",
        SUPERMERCADO,
        "Av. do Estado, 2400",
        "Barra",
        "Balneário Camboriú",
        "88330-090",
        -27.0000,
        -48.6200,
        "(47) 3367-2000",
        "DOCA_ELEVADA",
        "TOCO",
        [],
    ),
    # ---------------------------------------------------------------- Camboriú
    (
        "CUST-CAM-001",
        "Atacadão Camboriú - Tabuleiro",
        ATACADO,
        "Rua Lauro Loyola, 800",
        "Tabuleiro",
        "Camboriú",
        "88345-000",
        -27.0290,
        -48.6650,
        "(47) 3365-1000",
        "DOCA_ELEVADA",
        "TRUCK",
        [_MORNING_DOCK_RULE],
    ),
    (
        "CUST-CAM-002",
        "Mercearia Monte Alegre",
        MERCEARIA,
        "Rua João Sebastião da Silva, 150",
        "Monte Alegre",
        "Camboriú",
        "88348-000",
        -27.0230,
        -48.6720,
        "(47) 3365-1100",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    (
        "CUST-CAM-003",
        "Supermercado Cooper - Camboriú Centro",
        SUPERMERCADO,
        "Av. Santa Catarina, 300",
        "Centro",
        "Camboriú",
        "88340-000",
        -27.0250,
        -48.6560,
        "(47) 3365-1200",
        "DOCA_ELEVADA",
        "TRUCK",
        [],
    ),
    (
        "CUST-CAM-004",
        "Açougue Santa Regina",
        ACOUGUE,
        "Rua Santa Regina, 75",
        "Santa Regina",
        "Camboriú",
        "88349-000",
        -27.0400,
        -48.6600,
        "(47) 3365-1300",
        "NIVEL_SOLO",
        "TOCO",
        [],
    ),
    (
        "CUST-CAM-005",
        "Mercearia Cedro",
        MERCEARIA,
        "Rua Cedro, 410",
        "Cedro",
        "Camboriú",
        "88346-000",
        -27.0170,
        -48.6800,
        "(47) 3365-1400",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    # -------------------------------------------------------------- Navegantes
    (
        "CUST-NAV-001",
        "Komprão Koch Atacadista - Gravatá",
        ATACADO,
        "Av. Prefeito José Juvenal Mafra, 3000",
        "Gravatá",
        "Navegantes",
        "88375-000",
        -26.8680,
        -48.6400,
        "(47) 3342-1000",
        "DOCA_ELEVADA",
        "TRUCK",
        [_MORNING_DOCK_RULE, _COLD_CHAIN_RULE],
    ),
    (
        "CUST-NAV-002",
        "Supermercado Koch - Navegantes Centro",
        SUPERMERCADO,
        "Rua João Emílio, 200",
        "Centro",
        "Navegantes",
        "88370-000",
        -26.8990,
        -48.6540,
        "(47) 3342-1100",
        "DOCA_ELEVADA",
        "TRUCK",
        [],
    ),
    (
        "CUST-NAV-003",
        "Mercearia São Domingos",
        MERCEARIA,
        "Rua Nossa Senhora de Fátima, 88",
        "São Domingos",
        "Navegantes",
        "88372-000",
        -26.8840,
        -48.6620,
        "(47) 3342-1200",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    (
        "CUST-NAV-004",
        "Peixaria & Frios Meia Praia",
        PEIXARIA,
        "Av. Prefeito José Juvenal Mafra, 5500",
        "Meia Praia",
        "Navegantes",
        "88376-000",
        -26.8560,
        -48.6380,
        "(47) 3342-1300",
        "NIVEL_SOLO",
        "TOCO",
        [_COLD_CHAIN_RULE],
    ),
    (
        "CUST-NAV-005",
        "Minimercado Machados",
        MINIMERCADO,
        "Rua Sebastião Cardoso, 270",
        "Machados",
        "Navegantes",
        "88373-000",
        -26.8750,
        -48.6700,
        "(47) 3342-1400",
        "NIVEL_SOLO",
        "TOCO",
        [],
    ),
    (
        "CUST-NAV-006",
        "Padaria Pão Quente Navegantes",
        PADARIA,
        "Rua Pedro Rodrigues, 130",
        "Centro",
        "Navegantes",
        "88370-100",
        -26.8960,
        -48.6500,
        "(47) 3342-1500",
        "SEM_DOCA",
        "VUC",
        [_EARLY_DOCK_RULE, _VUC_ONLY_RULE],
    ),
    (
        "CUST-NAV-007",
        "Conveniência Aeroporto Navegantes",
        CONVENIENCIA,
        "Rua Osmar Gaya, 900",
        "Centro",
        "Navegantes",
        "88370-200",
        -26.8800,
        -48.6450,
        "(47) 3342-1600",
        "SEM_DOCA",
        "VUC",
        [_QUICK_UNLOAD_RULE],
    ),
    # --------------------------------------------------------- Penha / Piçarras
    (
        "CUST-PEN-001",
        "Supermercado Bistek - Penha Centro",
        SUPERMERCADO,
        "Av. Nereu Ramos, 1000",
        "Centro",
        "Penha",
        "88385-000",
        -26.7730,
        -48.6480,
        "(47) 3345-1000",
        "DOCA_ELEVADA",
        "TOCO",
        [],
    ),
    (
        "CUST-PEN-002",
        "Mercearia Armação",
        MERCEARIA,
        "Rua Manoel Francisco Ribeiro, 45",
        "Armação do Itapocorói",
        "Penha",
        "88385-300",
        -26.7800,
        -48.5980,
        "(47) 3345-1100",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    (
        "CUST-PIC-001",
        "Minimercado Praia de Piçarras",
        MINIMERCADO,
        "Av. Emanoel Pinto, 500",
        "Centro",
        "Balneário Piçarras",
        "88380-000",
        -26.7640,
        -48.6690,
        "(47) 3347-1000",
        "NIVEL_SOLO",
        "TOCO",
        [],
    ),
    # ------------------------------------------------------------------ Brusque
    (
        "CUST-BRU-001",
        "Cooper Supermercado - Brusque Centro",
        SUPERMERCADO,
        "Av. Cônsul Carlos Renaux, 200",
        "Centro",
        "Brusque",
        "88350-000",
        -27.0980,
        -48.9130,
        "(47) 3351-1000",
        "DOCA_ELEVADA",
        "TRUCK",
        [],
    ),
    (
        "CUST-BRU-002",
        "Komprão Koch Atacadista - Santa Rita",
        ATACADO,
        "Rod. Antônio Heil, 2000",
        "Santa Rita",
        "Brusque",
        "88353-100",
        -27.0800,
        -48.9000,
        "(47) 3351-1100",
        "DOCA_ELEVADA",
        "TRUCK",
        [_MORNING_DOCK_RULE],
    ),
    (
        "CUST-BRU-003",
        "Bistek Supermercados - Centro II",
        SUPERMERCADO,
        "Rua Hercílio Luz, 300",
        "Centro II",
        "Brusque",
        "88352-000",
        -27.1010,
        -48.9200,
        "(47) 3351-1200",
        "DOCA_ELEVADA",
        "TOCO",
        [],
    ),
    (
        "CUST-BRU-004",
        "Archer Supermercados - Jardim Maluche",
        SUPERMERCADO,
        "Av. Primeiro de Maio, 900",
        "Jardim Maluche",
        "Brusque",
        "88354-200",
        -27.1120,
        -48.9250,
        "(47) 3351-1300",
        "DOCA_ELEVADA",
        "TRUCK",
        [_COLD_CHAIN_RULE],
    ),
    (
        "CUST-BRU-005",
        "Mercearia Águas Claras",
        MERCEARIA,
        "Rua Mário Reinke, 60",
        "Águas Claras",
        "Brusque",
        "88355-000",
        -27.0900,
        -48.9350,
        "(47) 3351-1400",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE],
    ),
    (
        "CUST-BRU-006",
        "Açougue & Frios Steffen",
        ACOUGUE,
        "Rua Otto Renaux, 510",
        "Steffen",
        "Brusque",
        "88352-300",
        -27.0850,
        -48.9160,
        "(47) 3351-1500",
        "NIVEL_SOLO",
        "VUC",
        [_VUC_ONLY_RULE, _COLD_CHAIN_RULE],
    ),
    (
        "CUST-BRU-007",
        "Padaria Bela Vista Brusque",
        PADARIA,
        "Rua Carlos Boos, 220",
        "Bela Vista",
        "Brusque",
        "88353-300",
        -27.1040,
        -48.9050,
        "(47) 3351-1600",
        "SEM_DOCA",
        "VUC",
        [_EARLY_DOCK_RULE, _VUC_ONLY_RULE],
    ),
    (
        "CUST-BRU-008",
        "Hortifruti Cedro Alto",
        HORTIFRUTI,
        "Rua Ivo Reis Montenegro, 1300",
        "Cedro Alto",
        "Brusque",
        "88356-000",
        -27.0700,
        -48.9250,
        "(47) 3351-1700",
        "NIVEL_SOLO",
        "TOCO",
        [],
    ),
    (
        "CUST-BRU-009",
        "Supermercado Imperatriz - Azambuja",
        SUPERMERCADO,
        "Rua Azambuja, 1500",
        "Azambuja",
        "Brusque",
        "88354-000",
        -27.1180,
        -48.8990,
        "(47) 3351-1800",
        "DOCA_ELEVADA",
        "TOCO",
        [],
    ),
]


def _cnpj_for(code: str) -> str:
    """Illustrative, well-formed CNPJ derived from the customer code (not a real registration)."""
    seq = int(hashlib.sha256(code.encode("utf-8")).hexdigest(), 16) % 10**12
    base = f"{seq:012d}"
    return f"{base[:2]}.{base[2:5]}.{base[5:8]}/{base[8:12]}-{seq % 97:02d}"


def _expand(row: tuple[Any, ...]) -> dict[str, Any]:
    code, name, segment, street, hood, city, zip_code, lat, lng, phone, dock_type, max_vehicle, rules = row
    return {
        "code": code,
        "name": name,
        "segment": segment,
        "document_cnpj": _cnpj_for(code),
        "address": street,
        "neighborhood": hood,
        "city": city,
        "state": "SC",
        "zip_code": zip_code,
        "lat": lat,
        "lng": lng,
        "contact_phone": phone,
        "dock_type": dock_type,
        "max_vehicle_allowed": max_vehicle,
        "rules": [dict(r) for r in rules],
    }


REGIONAL_CUSTOMERS_POOL: list[dict[str, Any]] = [_expand(r) for r in _RAW]

__all__ = ["REGIONAL_CUSTOMERS_POOL", "SEGMENTS"]
