"""
Regional Customer and Destination Address Pool for Itajaí and Coastal Hubs.
Provides realistic geolocated business destinations across Itajaí, Balneário Camboriú, Navegantes, and Camboriú.
"""

from typing import Any, Dict, List

REGIONAL_CUSTOMERS_POOL: List[Dict[str, Any]] = [
    {
        "code": "CUST-ITJ-001",
        "name": "Supermercado Bistek - Fazenda",
        "document_cnpj": "83.261.411/0001-92",
        "address": "Rua Sete de Setembro, 1200",
        "neighborhood": "Fazenda",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88301-202",
        "lat": -26.9185,
        "lng": -48.6492,
        "contact_phone": "(47) 3348-1000",
        "dock_type": "RAMPA_ESTREITA",
        "max_vehicle_allowed": "VUC",
        "rules": [
            {
                "category": "ACCESS_RESTRICTION",
                "content": "Rua residencial e rampa de doca estreita no bairro Fazenda. Apenas veículos VUC autorizados. Proibido caminhão Truck.",
                "priority": "CRITICAL",
            }
        ],
    },
    {
        "code": "CUST-ITJ-002",
        "name": "Komprão Koch Atacadista - Cordeiros",
        "document_cnpj": "02.831.356/0014-50",
        "address": "Av. Reinaldo Schmithausen, 1850",
        "neighborhood": "Cordeiros",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88310-001",
        "lat": -26.8820,
        "lng": -48.6875,
        "contact_phone": "(47) 3249-5500",
        "dock_type": "ELEVADA",
        "max_vehicle_allowed": "TOCO",
        "rules": [
            {
                "category": "DOCK_WINDOW",
                "content": "Fila severa de carretas na Av. Reinaldo Schmithausen após 09:00. Priorizar descarga entre 06:00 e 08:30.",
                "priority": "HIGH",
            }
        ],
    },
    {
        "code": "CUST-ITJ-003",
        "name": "Pescados & Frigorífico Costa Sul - Porto",
        "document_cnpj": "04.112.980/0001-33",
        "address": "Rua Pedro Ferreira, 350",
        "neighborhood": "Centro / Porto",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88301-030",
        "lat": -26.9070,
        "lng": -48.6540,
        "contact_phone": "(47) 3341-8200",
        "dock_type": "DOCA_FRIGORIFICADA",
        "max_vehicle_allowed": "VUC",
        "rules": [
            {
                "category": "COLD_CHAIN",
                "content": "Exige controle estrito de cadeia de frio. Conferência de temperatura obrigatória antes do descarregamento na doca portuária.",
                "priority": "CRITICAL",
            }
        ],
    },
    {
        "code": "CUST-BC-004",
        "name": "Angeloni Supermercados - Quarta Avenida",
        "document_cnpj": "83.646.984/0022-18",
        "address": "Quarta Avenida, 880",
        "neighborhood": "Centro",
        "city": "Balneário Camboriú",
        "state": "SC",
        "zip_code": "88330-110",
        "lat": -26.9910,
        "lng": -48.6360,
        "contact_phone": "(47) 3263-4000",
        "dock_type": "SUBSOLO_LIMITADO",
        "max_vehicle_allowed": "VUC",
        "rules": [
            {
                "category": "TIME_WINDOW_TRAFFIC",
                "content": "Trânsito de entrada em Balneário Camboriú complica após 08:30 pela BR-101. Agendar primeira parada da manhã.",
                "priority": "HIGH",
            }
        ],
    },
    {
        "code": "CUST-ITJ-005",
        "name": "Farmácia Preço Popular - São Vicente",
        "document_cnpj": "84.307.848/0055-60",
        "address": "Rua Estefano José Vanolli, 920",
        "neighborhood": "São Vicente",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88309-000",
        "lat": -26.9045,
        "lng": -48.6935,
        "contact_phone": "(47) 3346-7788",
        "dock_type": "NIVEL_SOLO",
        "max_vehicle_allowed": "VUC",
        "rules": [],
    },
    {
        "code": "CUST-ITJ-006",
        "name": "Armazém & Adega Brava Beach",
        "document_cnpj": "31.450.890/0001-12",
        "address": "Av. José Medeiros Vieira, 1400",
        "neighborhood": "Praia Brava",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88306-800",
        "lat": -26.9530,
        "lng": -48.6280,
        "contact_phone": "(47) 3344-9900",
        "dock_type": "LATERAL_SERVICO",
        "max_vehicle_allowed": "VUC",
        "rules": [
            {
                "category": "SECURITY_AND_RESTRICTION",
                "content": "Av. da praia tem restrição diurna para caminhões pesados. Apenas VUC autorizado. Carga de alto valor (vinhos e destilados finos).",
                "priority": "CRITICAL",
            }
        ],
    },
    {
        "code": "CUST-ITJ-007",
        "name": "Fort Atacadista - Ressacada",
        "document_cnpj": "09.477.652/0038-70",
        "address": "Rua Tijucas, 1050",
        "neighborhood": "Ressacada",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88307-300",
        "lat": -26.9160,
        "lng": -48.6780,
        "contact_phone": "(47) 3349-2233",
        "dock_type": "ELEVADA",
        "max_vehicle_allowed": "TOCO",
        "rules": [],
    },
    {
        "code": "CUST-NAV-008",
        "name": "Supermercado Koch - Navegantes Centro",
        "document_cnpj": "02.831.356/0008-01",
        "address": "Av. Prefeito Cirino Adolfo Cabral, 450",
        "neighborhood": "Centro",
        "city": "Navegantes",
        "state": "SC",
        "zip_code": "88370-000",
        "lat": -26.8920,
        "lng": -48.6510,
        "contact_phone": "(47) 3342-1200",
        "dock_type": "NIVEL_SOLO",
        "max_vehicle_allowed": "TOCO",
        "rules": [],
    },
    {
        "code": "CUST-BC-009",
        "name": "Supermercado De Angelina - Barra Norte",
        "document_cnpj": "14.288.940/0001-44",
        "address": "Av. Brasil, 250",
        "neighborhood": "Barra Norte",
        "city": "Balneário Camboriú",
        "state": "SC",
        "zip_code": "88338-005",
        "lat": -26.9740,
        "lng": -48.6325,
        "contact_phone": "(47) 3367-1520",
        "dock_type": "SUBSOLO_LIMITADO",
        "max_vehicle_allowed": "VUC",
        "rules": [
            {
                "category": "ACCESS_RESTRICTION",
                "content": "Acesso pela Av. Brasil com tráfego intenso. Permitido apenas VUC com altura máxima de 3,20m.",
                "priority": "HIGH",
            }
        ],
    },
    {
        "code": "CUST-ITJ-010",
        "name": "Havan Itajaí - Vila Operária",
        "document_cnpj": "79.379.491/0008-33",
        "address": "Rua Heitor Liberato, 1550",
        "neighborhood": "Vila Operária",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88303-100",
        "lat": -26.9025,
        "lng": -48.6720,
        "contact_phone": "(47) 3247-4000",
        "dock_type": "ELEVADA",
        "max_vehicle_allowed": "TRUCK",
        "rules": [],
    },
    {
        "code": "CUST-ITJ-011",
        "name": "Cooper Supermercado - Brusque",
        "document_cnpj": "82.639.290/0012-70",
        "address": "Rua Brusque, 1050",
        "neighborhood": "Centro",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88303-000",
        "lat": -26.9140,
        "lng": -48.6670,
        "contact_phone": "(47) 3341-9800",
        "dock_type": "NIVEL_SOLO",
        "max_vehicle_allowed": "TOCO",
        "rules": [],
    },
    {
        "code": "CUST-ITJ-012",
        "name": "Giassi Supermercados - Almirante Barroso",
        "document_cnpj": "83.649.376/0015-88",
        "address": "Rua Almirante Barroso, 850",
        "neighborhood": "Fazenda",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88301-600",
        "lat": -26.9190,
        "lng": -48.6570,
        "contact_phone": "(47) 3348-4300",
        "dock_type": "ELEVADA",
        "max_vehicle_allowed": "TOCO",
        "rules": [],
    },
    {
        "code": "CUST-ITJ-013",
        "name": "Distribuidora Santa Catarina Bebidas",
        "document_cnpj": "08.921.433/0001-52",
        "address": "Rua Dr. Reinaldo Schmithausen, 2800",
        "neighborhood": "Cordeiros",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88310-004",
        "lat": -26.8770,
        "lng": -48.6990,
        "contact_phone": "(47) 3241-7700",
        "dock_type": "ELEVADA",
        "max_vehicle_allowed": "TRUCK",
        "rules": [],
    },
    {
        "code": "CUST-BC-014",
        "name": "Balaroti Materiais de Construção - Av. do Estado",
        "document_cnpj": "75.767.897/0034-21",
        "address": "Av. do Estado Dalmo Vieira, 2100",
        "neighborhood": "Pioneiros",
        "city": "Balneário Camboriú",
        "state": "SC",
        "zip_code": "88331-440",
        "lat": -26.9790,
        "lng": -48.6410,
        "contact_phone": "(47) 3261-2200",
        "dock_type": "NIVEL_SOLO",
        "max_vehicle_allowed": "TOCO",
        "rules": [],
    },
    {
        "code": "CUST-BC-015",
        "name": "Restaurante & Gastronomia Passeio San Miguel",
        "document_cnpj": "23.512.879/0001-90",
        "address": "Av. Brasil, 3322",
        "neighborhood": "Centro",
        "city": "Balneário Camboriú",
        "state": "SC",
        "zip_code": "88330-058",
        "lat": -27.0065,
        "lng": -48.6260,
        "contact_phone": "(47) 3367-7788",
        "dock_type": "LATERAL_SERVICO",
        "max_vehicle_allowed": "VUC",
        "rules": [
            {
                "category": "ACCESS_RESTRICTION",
                "content": "Pátio comercial compartilhado. Entrega permitida somente por VUC até 10:30 para evitar fluxo de clientes.",
                "priority": "HIGH",
            }
        ],
    },
    {
        "code": "CUST-ITJ-016",
        "name": "Hospital e Maternidade Marieta Konder",
        "document_cnpj": "84.301.593/0001-19",
        "address": "Av. Marcos Konder, 1111",
        "neighborhood": "Centro",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88301-303",
        "lat": -26.9065,
        "lng": -48.6610,
        "contact_phone": "(47) 3249-9400",
        "dock_type": "DOCA_HOSPITALAR",
        "max_vehicle_allowed": "VUC",
        "rules": [
            {
                "category": "SECURITY_AND_RESTRICTION",
                "content": "Doca hospitalar com controle sanitário. Prioridade absoluta para medicamentos e insumos críticos.",
                "priority": "CRITICAL",
            }
        ],
    },
    {
        "code": "CUST-NAV-017",
        "name": "Komprão Koch Atacadista - Gravatá",
        "document_cnpj": "02.831.356/0019-64",
        "address": "Rua José Juvenal Mafra, 7500",
        "neighborhood": "Gravatá",
        "city": "Navegantes",
        "state": "SC",
        "zip_code": "88372-500",
        "lat": -26.8390,
        "lng": -48.6315,
        "contact_phone": "(47) 3349-8800",
        "dock_type": "ELEVADA",
        "max_vehicle_allowed": "TRUCK",
        "rules": [],
    },
    {
        "code": "CUST-CAM-018",
        "name": "Atacadão Camboriú - Tabuleiro",
        "document_cnpj": "75.315.333/0142-90",
        "address": "Rua Santa Paulina, 120",
        "neighborhood": "Tabuleiro",
        "city": "Camboriú",
        "state": "SC",
        "zip_code": "88348-150",
        "lat": -27.0090,
        "lng": -48.6580,
        "contact_phone": "(47) 3365-1020",
        "dock_type": "ELEVADA",
        "max_vehicle_allowed": "TRUCK",
        "rules": [],
    },
    {
        "code": "CUST-ITJ-019",
        "name": "Mercado Público & Marina de Itajaí",
        "document_cnpj": "11.234.567/0001-88",
        "address": "Av. Min. Victor Konder, 1300",
        "neighborhood": "Centro",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88301-700",
        "lat": -26.9085,
        "lng": -48.6500,
        "contact_phone": "(47) 3348-2300",
        "dock_type": "LATERAL_SERVICO",
        "max_vehicle_allowed": "VUC",
        "rules": [],
    },
    {
        "code": "CUST-BC-020",
        "name": "Balneário Shopping - Lojas Âncora",
        "document_cnpj": "08.452.123/0002-45",
        "address": "Av. Santa Catarina, 1",
        "neighborhood": "Estados",
        "city": "Balneário Camboriú",
        "state": "SC",
        "zip_code": "88339-900",
        "lat": -26.9960,
        "lng": -48.6470,
        "contact_phone": "(47) 3263-8000",
        "dock_type": "ELEVADA",
        "max_vehicle_allowed": "TOCO",
        "rules": [
            {
                "category": "DOCK_WINDOW",
                "content": "Doca do shopping opera rigorosamente para recebimento entre 07:00 e 11:00.",
                "priority": "HIGH",
            }
        ],
    },
    {
        "code": "CUST-ITJ-021",
        "name": "Padaria & Empório São Chico - Carvalho",
        "document_cnpj": "27.890.123/0001-34",
        "address": "Av. Ver. Abrahão João Francisco, 1800",
        "neighborhood": "Carvalho",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88307-001",
        "lat": -26.9120,
        "lng": -48.6810,
        "contact_phone": "(47) 3346-5511",
        "dock_type": "NIVEL_SOLO",
        "max_vehicle_allowed": "VUC",
        "rules": [],
    },
    {
        "code": "CUST-BC-022",
        "name": "Drogaria Catarinense - Centro BC",
        "document_cnpj": "84.307.848/0029-79",
        "address": "Av. Brasil, 1500",
        "neighborhood": "Centro",
        "city": "Balneário Camboriú",
        "state": "SC",
        "zip_code": "88330-048",
        "lat": -26.9880,
        "lng": -48.6320,
        "contact_phone": "(47) 3367-2000",
        "dock_type": "NIVEL_SOLO",
        "max_vehicle_allowed": "VUC",
        "rules": [],
    },
    {
        "code": "CUST-ITJ-023",
        "name": "Distribuidora Hortifruti Vale - Espinheiros",
        "document_cnpj": "18.345.678/0001-99",
        "address": "Rod. Jorge Lacerda, 450",
        "neighborhood": "Espinheiros",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88317-100",
        "lat": -26.8950,
        "lng": -48.7230,
        "contact_phone": "(47) 3344-1234",
        "dock_type": "DOCA_FRIGORIFICADA",
        "max_vehicle_allowed": "TRUCK",
        "rules": [],
    },
    {
        "code": "CUST-ITJ-024",
        "name": "Boutique de Carnes Dom Bosco",
        "document_cnpj": "34.567.890/0001-12",
        "address": "Rua Indaial, 850",
        "neighborhood": "Dom Bosco",
        "city": "Itajaí",
        "state": "SC",
        "zip_code": "88303-300",
        "lat": -26.9230,
        "lng": -48.6790,
        "contact_phone": "(47) 3348-7711",
        "dock_type": "NIVEL_SOLO",
        "max_vehicle_allowed": "VUC",
        "rules": [
            {
                "category": "COLD_CHAIN",
                "content": "Recebimento de carnes nobres resfriadas. Caminhão com termômetro calibrado obrigatório.",
                "priority": "HIGH",
            }
        ],
    },
]
